# Lexik JWT Authentication
lexik_jwt_authentication:
    private_key_path:   %private_key_path%
    public_key_path:    %public_key_path%
    pass_phrase:        %pass_phrase%
    token_ttl:          %token_ttl%

sensio_framework_extra:
    view:    { annotations: false }
    router:  { annotations: true }
    request: { converters: true }

# JMS Serializer
jms_serializer:
    metadata:
        auto_detection: true

# FOS Rest
fos_rest:
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: false }
            - { path: '^/', priorities: ['html'], fallback_format: html, prefer_extension: false }
    view:
        view_response_listener: force
        formats:
            json: true
            xml:  false
        # jsonp_handler: ~
    routing_loader:
        default_format: json
    serializer:
        serialize_null: true
    param_fetcher_listener: true
    body_converter:
        enabled: true
    body_listener:
        array_normalizer: fos_rest.normalizer.camel_keys
    # disable_csrf_role: ROLE_USER
    access_denied_listener:
        json: true

# Cors
nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600

