app_seccion_doce_api:
    resource: "@AppBundle/Controller/SeccionDoceRESTController.php"
    type:   rest
    prefix:   /api

app_aldea_turno_api:
    resource: "@AppBundle/Controller/AldeaTurnoRESTController.php"
    type:   rest
    prefix:   /api

app_ajuste_api:
    resource: "@AppBundle/Controller/AjusteRESTController.php"
    type:   rest
    prefix:   /api

app_report:
    type:     annotation
    resource: "@AppBundle/Controller/ConsultasREPORTController.php"

app_pnf_trayecto_periodo_uc_api:
    resource: "@AppBundle/Controller/PnfTrayectoPeriodoUcRESTController.php"
    type:   rest
    prefix:   /api

app_pnf_trayecto_periodo_api:
    resource: "@AppBundle/Controller/PnfTrayectoPeriodoRESTController.php"
    type:   rest
    prefix:   /api

app_aldea_api:
    resource: "@AppBundle/Controller/AldeaRESTController.php"
    type:   rest
    prefix:   /api

app_periodo_academico_api:
    resource: "@AppBundle/Controller/PeriodoAcademicoRESTController.php"
    type:   rest
    prefix:   /api

app_estu_pnf_api:
    resource: "@AppBundle/Controller/EstuPnfRESTController.php"
    type:   rest
    prefix:   /api

app_seccion_api:
    resource: "@AppBundle/Controller/SeccionRESTController.php"
    type:   rest
    prefix:   /api

app_pnf_tipo_api:
    resource: "@AppBundle/Controller/PnfTipoRESTController.php"
    type:   rest
    prefix:   /api

app_trayecto_api:
    resource: "@AppBundle/Controller/TrayectoRESTController.php"
    type:   rest
    prefix:   /api

app_periodo_api:
    resource: "@AppBundle/Controller/PeriodoRESTController.php"
    type:   rest
    prefix:   /api

app_turno_api:
    resource: "@AppBundle/Controller/TurnoRESTController.php"
    type:   rest
    prefix:   /api

app_unidad_curricular_api:
    resource: "@AppBundle/Controller/UnidadCurricularRESTController.php"
    type:   rest
    prefix:   /api

app_docente_api:
    resource: "@AppBundle/Controller/DocenteRESTController.php"
    type:   rest
    prefix:   /api

app_estudiante_api:
    resource: "@AppBundle/Controller/EstudianteRESTController.php"
    type:   rest
    prefix:   /api

app_pnf_api:
    resource: "@AppBundle/Controller/PnfRESTController.php"
    type:   rest
    prefix:   /api

app_resetting_api:
    resource: "@AppBundle/Controller/ResettingRESTController.php"
    type:   rest
    prefix:   /api

app_registration_api:
    resource: "@AppBundle/Controller/RegistrationRESTController.php"
    type:   rest
    prefix:   /api

app_change_password_api:
    resource: "@AppBundle/Controller/ChangePasswordRESTController.php"
    type:   rest
    prefix:   /api

app_profile_api:
    resource: "@AppBundle/Controller/ProfileRESTController.php"
    type:   rest
    prefix:   /api

app_user_api:
    resource: "@AppBundle/Controller/UserRESTController.php"
    type:   rest
    prefix:   /api


app_zona_api:
    resource: "@AppBundle/Controller/ZonaRESTController.php"
    type:   rest
    prefix:   /api

app_parroquia_api:
    resource: "@AppBundle/Controller/ParroquiaRESTController.php"
    type:   rest
    prefix:   /api

app_municipio_api:
    resource: "@AppBundle/Controller/MunicipioRESTController.php"
    type:   rest
    prefix:   /api

app_estado_api:
    resource: "@AppBundle/Controller/EstadoRESTController.php"
    type:   rest
    prefix:   /api

app_pais_api:
    resource: "@AppBundle/Controller/PaisRESTController.php"
    type:   rest
    prefix:   /api


app:
    type:     annotation
    resource: "@AppBundle/Controller/DefaultController.php"

app_api:
    resource: routing_api.yml
    prefix: /api


#FOS User routing
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# Doc Api
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc

# translation
_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"