app_resetting_api:
    resource: "@AppBundle/Controller/ResettingRESTController.php"
    type:   rest
    prefix:   /api

app_registration_api:
    resource: "@AppBundle/Controller/RegistrationRESTController.php"
    type:   rest
    prefix:   /api

app_change_password_api:
    resource: "@AppBundle/Controller/ChangePasswordRESTController.php"
    type:   rest
    prefix:   /api

app_profile_api:
    resource: "@AppBundle/Controller/ProfileRESTController.php"
    type:   rest
    prefix:   /api

app_user_api:
    resource: "@AppBundle/Controller/UserRESTController.php"
    type:   rest
    prefix:   /api


app_zona_api:
    resource: "@AppBundle/Controller/ZonaRESTController.php"
    type:   rest
    prefix:   /api

app_parroquia_api:
    resource: "@AppBundle/Controller/ParroquiaRESTController.php"
    type:   rest
    prefix:   /api

app_municipio_api:
    resource: "@AppBundle/Controller/MunicipioRESTController.php"
    type:   rest
    prefix:   /api

app_estado_api:
    resource: "@AppBundle/Controller/EstadoRESTController.php"
    type:   rest
    prefix:   /api

app_pais_api:
    resource: "@AppBundle/Controller/PaisRESTController.php"
    type:   rest
    prefix:   /api


app:
    type:     annotation
    resource: "@AppBundle/Controller/DefaultController.php"

app_api:
    resource: routing_api.yml
    prefix: /api


#FOS User routing
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# Doc Api
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc

# translation
_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"